# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf35dce33998ba513cd32e6a590fb145b2951597ea9cbfbf7627a7871dd48957252b48d14b0e0b60fb41c33d1555b8fd2debadc3f5bda737ae44cd713bc42169

test:
  secret_key_base: 24935f00183f882d23a529e7a80df8e072d233413147996087a160e85da20ea94466f689d67a2ead2d340b727922a04e265ce9512c5fb51bfdcc4a9ea80cfb78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
